name: Maven Package

on:
  push:
    branches: [main]
    paths:
      - '**.java'
      - 'pom.xml'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy Maven settings
        run: |
          mkdir -p $HOME/.m2
          cp .github/settings.xml $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Run unit tests
        run: mvn test

      - name: Publish to GitHub Packages
        
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
